name: Openwrt Build v23.05.5

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: apt update and install
      run: sudo apt update && sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
    - name: git clone openwrt
      run: |
        git clone --branch v23.05.3 --depth 1 https://git.openwrt.org/openwrt/openwrt.git
    - name: openwrt feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        cat .config
    - name: Store packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: |
          openwrt/
